/**
 * EXPERIMENTAL — AI-authored decision candidates, generated by the same local
 * llama.cpp/Qwen3-1.7B server `llmService.ts` already uses for annual-report flavor
 * text (see docker-compose.yml's `llm` service). Unlike that module, this one asks the
 * model to invent real game mechanics (a `DecisionDefinition` with its own
 * `legalRisks`), not just narrate an existing one — a categorically bigger ask of a
 * 1.7B model, so nothing this module produces is ever written to the DB or a live game
 * on its own. A candidate only ever reaches an admin's review textarea
 * (`POST /api/admin/decisions/generate`); saving it still goes through the exact same
 * `decisionDefinitionSchema`-gated `POST /api/admin/decisions` a hand-written decision
 * would. See CLAUDE.md's "AI decision generation (experimental)" section for the
 * verdict on whether the model is actually good enough at this.
 *
 * Deliberately NOT best-effort/fallback-silent like `llmService.ts` — there's no
 * static fallback text for "a whole invented decision," so a failure here is a real
 * error surfaced to the admin, not swallowed.
 */

import type { DecisionDefinition } from '@suetheirasses/shared';
import { decisionDefinitionSchema } from '../validation/schemas.js';
import { clampDecisionCandidate, isViableCandidate, type ClampWarning } from './decisionGenGuardrails.js';

const LLM_URL = process.env.LLM_URL || 'http://localhost:8080';
/** Generous — an eval run against the real CPU-only container (Qwen3-1.7B-Q4, no GPU)
 * showed ~50s for a typical ~300-token decision+legal-risk JSON response, with a cold
 * KV-cache miss on the (long, mostly-static) system prompt costing another ~15-20s of
 * prompt processing on top. A 30s timeout aborted every single attempt in that eval. */
const REQUEST_TIMEOUT_MS = 120_000;
const MAX_ATTEMPTS = 3;

export interface DecisionGenRequest {
  /** Free-text theme/prompt hint, e.g. "supply chain sabotage" or "a green PR stunt". */
  theme?: string;
  level?: 'Strategic' | 'Operational' | 'Financial';
  nature?: 'Traditional' | 'Grey Area' | 'Dirty';
  /** Hint that this should be a `target.*`-bearing attack on a chosen opponent. */
  offensive?: boolean;
}

export type DecisionGenResult =
  | { success: true; decision: DecisionDefinition; warnings: ClampWarning[]; attempts: number }
  | { success: false; error: string; raw?: string; attempts: number };

const FIELD_CHEATSHEET = `Field magnitude cheat-sheet (typical ranges seen in the real decision library):
- cash (absolute, dollars): -150000 to 250000
- operatingExpenses / staffCost / assets / debt (absolute, dollars): tens of thousands, e.g. -60000 to 80000
- price / capacityUtilization / supplySecurity / energyIntensity / installedCapacity (relative, a fraction added to 1.0): -0.3 to 0.4
- processingLevel / moistureContent / processLoss / nutrientConsistency (absolute, 0-1 scale): -0.2 to 0.3
- outrage / scrutiny / carbonFootprint / demand (absolute, point scale): -40 to 40
Legal risk stakes: 'cash' target (absolute dollars): -300000 to -20000. 'equity'/'revenue' target (relative fraction of the defendant's own current value): -0.5 to -0.05. Probability values: 0.02 to 0.6.`;

function fewShotBlock(example: DecisionDefinition): string {
  // Trimmed to the fields that matter for shape — competitorsView/legalRiskConditions
  // omitted to keep the few-shot example short for a small model's context budget.
  const trimmed = {
    decision: example.decision,
    level: example.level,
    description: example.description,
    nature: example.nature,
    offensiveAction: example.offensiveAction,
    excludes: example.excludes,
    impacts: example.impacts,
    legalRisks: example.legalRisks,
    cashFlowCategory: (example as any).cashFlowCategory,
  };
  return JSON.stringify(trimmed, null, 2);
}

/**
 * Builds the system/user messages sent to the model. Exported (and pure — no network
 * I/O) so it can be unit-tested and iterated on without a running LLM.
 */
export function buildDecisionGenPrompt(
  request: DecisionGenRequest,
  existingDecisionNames: string[],
  fewShotExample: DecisionDefinition,
): { system: string; user: string } {
  const system = `You invent a new business decision for a corporate strategy game. Output ONLY one JSON object — no markdown fences, no explanation, no <think> block. /no_think

Required JSON shape:
{
  "decision": string (a short, punchy name, not already used),
  "level": "Strategic" | "Operational" | "Financial",
  "description": string (1-2 sentences, plain language),
  "nature": "Traditional" | "Grey Area" | "Dirty",
  "offensiveAction": boolean,
  "excludes": string[] (leave empty unless obviously conflicting with a real decision name given below),
  "impacts": { "<field>": { "type": "absolute" | "relative", "schedule": { "1": number, "2": number, "default": number } }, ... },
  "legalRisks": [ { "name": string, "description": string, "probability": { "1": number, "2": number, "default": number }, "impact": { "type": "absolute" | "relative", "target": "cash" | "equity" | "revenue", "schedule": { "1": number, "default": number } } } ],
  "cashFlowCategory": "operating" | "investing" | "financing" (only if impacts.cash is set)
}

Rules:
- "impacts" may ONLY use these field names, optionally prefixed "target." to route the effect at a chosen opponent instead of yourself: cash, assets, intangibleAssets, debt, reserves, operatingExpenses, staffCost, materialCostPerTon, otherIncome, price, capacityUtilization, processingLevel, energyIntensity, moistureContent, nutrientConsistency, supplySecurity, logisticsCostPerTon, processLoss, installedCapacity, outrage, scrutiny, breakdowns, contaminationRisk, odorComplaints, tokenLiability, carbonFootprint, stockVolume, demand, revenue, financeCost, taxCost.
- Use "target.<field>" ONLY for a decision that is a deliberate attack on one chosen opponent (set offensiveAction: true if you do). Otherwise never use a "target." field.
- Touch 2 to 4 fields in "impacts" total. Fewer, well-chosen effects are better than many small ones.
- "type": "absolute" means the number is added directly every year it applies. "relative" means the field is multiplied by (1 + number) — so 0.2 is +20%, -0.15 is -15%.
- Schedule keys are the string "1" (year 1 of having this decision active), optionally "2", and "default" (every year after that). Every impacts entry needs at least a "default" value.
- "legalRisks": 1 to 3 grounds another player could sue this decision over. "Traditional" nature should have 0-1 mild ground; "Grey Area" 1-2; "Dirty" 2-3 real ones. Each ground's "impact.target" must be "cash" (use "absolute") or "equity"/"revenue" (use "relative" — a fraction of the SUED PLAYER's own current value, always negative).
- "level": "Financial" is a separate per-turn budget from "Strategic"/"Operational", used for share-ownership/investment-flavored moves (e.g. hedging, financing, dividend-style plays) — only use it if asked to, or if the decision is clearly about trading/financial engineering rather than day-to-day operations or company strategy.
${FIELD_CHEATSHEET}

Example of the exact shape (do not copy this decision, invent a different one):
${fewShotBlock(fewShotExample)}`;

  const hints: string[] = [];
  if (request.theme) hints.push(`Theme: ${request.theme}.`);
  if (request.level) hints.push(`Level: ${request.level}.`);
  if (request.nature) hints.push(`Nature: ${request.nature}.`);
  if (request.offensive) hints.push('This should be a direct attack on one chosen opponent (use "target." fields, offensiveAction: true).');

  const avoidList = existingDecisionNames.length > 0
    ? `\nDo not reuse any of these existing decision names: ${existingDecisionNames.join(', ')}.`
    : '';

  const user = `Invent ONE new decision now. ${hints.join(' ')}${avoidList}\nOutput only the JSON object.`;

  return { system, user };
}

/** Strips Qwen3's optional `<think>...</think>` block, markdown code fences, and any
 * leading/trailing prose, then balance-matches the first `{...}` block — a small model
 * frequently adds a stray sentence before or after the JSON despite instructions not to. */
export function extractJson(raw: string): unknown {
  let text = raw.replace(/<think>[\s\S]*?<\/think>/gi, '').trim();
  text = text.replace(/```(?:json)?/gi, '').trim();

  const start = text.indexOf('{');
  if (start === -1) throw new Error('No JSON object found in model output');

  let depth = 0;
  let end = -1;
  for (let i = start; i < text.length; i++) {
    if (text[i] === '{') depth++;
    else if (text[i] === '}') {
      depth--;
      if (depth === 0) {
        end = i;
        break;
      }
    }
  }
  if (end === -1) throw new Error('Unbalanced JSON object in model output');

  return JSON.parse(text.slice(start, end + 1));
}

async function callModel(system: string, user: string): Promise<string> {
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), REQUEST_TIMEOUT_MS);

  try {
    const response = await fetch(`${LLM_URL}/v1/chat/completions`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      signal: controller.signal,
      body: JSON.stringify({
        messages: [
          { role: 'system', content: system },
          { role: 'user', content: user },
        ],
        max_tokens: 700,
        temperature: 0.7,
      }),
    });
    if (!response.ok) throw new Error(`LLM server responded with status ${response.status}`);
    const data: any = await response.json();
    const content: string = data?.choices?.[0]?.message?.content ?? '';
    if (!content) throw new Error('Empty LLM response');
    return content;
  } finally {
    clearTimeout(timeout);
  }
}

/**
 * Generates one AI-authored decision candidate, retrying up to `MAX_ATTEMPTS` times on
 * a malformed/unparseable/unviable response before giving up. Every successful
 * candidate has already been through `decisionDefinitionSchema` AND
 * `clampDecisionCandidate` — the caller (the admin REST route) still never writes it to
 * the DB itself, only returns it for human review.
 */
export async function generateDecisionCandidate(
  request: DecisionGenRequest,
  existingDecisionNames: string[],
  fewShotExample: DecisionDefinition,
): Promise<DecisionGenResult> {
  let lastError = 'Unknown error';
  let lastRaw: string | undefined;

  for (let attempt = 1; attempt <= MAX_ATTEMPTS; attempt++) {
    try {
      const { system, user } = buildDecisionGenPrompt(request, existingDecisionNames, fewShotExample);
      const raw = await callModel(system, user);
      lastRaw = raw;

      const parsed = extractJson(raw);
      const schemaResult = decisionDefinitionSchema.safeParse(parsed);
      if (!schemaResult.success) {
        lastError = `Schema validation failed: ${schemaResult.error.message}`;
        continue;
      }

      const clamped = clampDecisionCandidate(schemaResult.data as DecisionDefinition, existingDecisionNames);
      if (!isViableCandidate(clamped)) {
        lastError = 'Generated decision had no viable impacts after guardrail filtering';
        continue;
      }

      return { success: true, decision: clamped.decision, warnings: clamped.warnings, attempts: attempt };
    } catch (error: any) {
      lastError = error?.message || String(error);
    }
  }

  return { success: false, error: lastError, raw: lastRaw, attempts: MAX_ATTEMPTS };
}
